### PR TITLE
Fix cookies

### LINKED ISSUE #22: Fix cookies

### PR DESCRIPTION
**Pull request by cristianbgp**
Closes #22

### CODE REVIEW

File: api/app/controllers/sessions_controller.rb [hunk 1]
```diff
@@ -17,7 +17,7 @@ def register
     if user.save
       render json: user
     else
-      render json: { errors: user.errors}, status: :bad_request
+      render json: { errors: user.errors.full_messages}, status: :bad_request
```
Comment (liannivin) [inline api/app/controllers/sessions_controller.rb]: Could you please explain what are you trying to do with `.full_messages`?

Comment (cristianbgp) [reply api/app/controllers/sessions_controller.rb]: It returns an array of strings with all the errors
